### ISSUE TITLE
can't start it up

### ISSUE THREAD

**Issue by pawel-yesware** [lorieri/deis-dashboard#1]
when i do git push deis master it won't start

f348aabb7ac1: Pull complete
Digest: sha256:ce0d195132cd70b9aa774412cadf785634514209e835919ee5c06d911b138810
Status: Downloaded newer image for google/golang:latest
 ---> f348aabb7ac1
Step 1 : RUN go get gopkg.in/redis.v2 github.com/coreos/go-etcd/etcd
 ---> Running in e52d1664ca26
 ---> 621bd328255b
Removing intermediate container e52d1664ca26
Step 2 : ADD . /
 ---> 7bff32e403ac
Removing intermediate container fa1328b2f0d0
Step 3 : RUN go build web.go
 ---> Running in e057267f6b00
stat web.go: no such file or directory
The command '/bin/sh -c go build web.go' returned a non-zero code: 1
To ssh://git@deis.yetihut.com:2222/deis-dashboard.git
- [new branch]      master -> master

**Comment by lorieri** [comment]
Hi,

Sorry for the delay.

I fixed the golang image to 1.3.1, should run now.

Any problem, please re-open this issue.

Thanks !
